### Basic RNN Deep Learning Model steps
1. Gather data
2. Preprocess & cleaning data
3. Feature engineering
4. Build a model
5. Save model into .h5 file
6. Load model from .h5 file

#### Import libraries

In [40]:
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from tensorflow.keras.layers import Dense, Input, Embedding, SimpleRNN
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
import pickle

In [2]:
train_data = pd.read_csv('twitter_training.csv')

In [3]:
train_data.head()

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
0,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
1,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
2,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
3,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...
4,2401,Borderlands,Positive,im getting into borderlands and i can murder y...

In [4]:
train_data.shape

(74681, 4)

In [5]:
# We use only 15000 samples to train the model to save time.
data = train_data.sample(15000, random_state=42)

In [6]:
data.shape

(15000, 4)

In [7]:
data

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
34877,6792,Fortnite,Irrelevant,went to go in george's room to find his door w...
21704,4115,CS-GO,Positive,Yo this looks LIT! Team:GO/Overwatch combo
47008,5665,HomeDepot,Negative,Pay attention executive administrators. While ...
7969,9369,Overwatch,Irrelevant,Guy looked at me and says my name was put on t...
454,2476,Borderlands,Positive,one
...,...,...,...,...
7757,9333,Overwatch,Positive,i can play overwatch again (bad)
3887,1872,CallOfDutyBlackopsColdWar,Negative,The base weapons of black ops Cold War are so ...
22629,4275,CS-GO,Neutral,Don'don t just jump me... @CSGO... is medal. t...
66836,7044,johnson&johnson,Irrelevant,for FUCKS SAKE!!!!!!!! FIRST MONTH FOR ONE MON...
56434,11284,TomClancysRainbowSix,Positive,New video later shoot premiere at 12 and its g...

### Data exploration

In [8]:
# Check null values
data.isnull().sum()

2401                                                       0
Borderlands                                                0
Positive                                                   0
im getting on borderlands and i will murder you all ,    151
dtype: int64

In [9]:
# Check duplicate values
data.duplicated().sum()

np.int64(127)

In [10]:
# Check positive column different values
data['Positive'].value_counts()

Positive
Negative      4488
Positive      4275
Neutral       3568
Irrelevant    2669
Name: count, dtype: int64

### Drop unwanted columns and cleaning data

In [11]:
data.drop(columns=['2401', 'Borderlands'], inplace=True)

In [12]:
data

         Positive im getting on borderlands and i will murder you all ,
34877  Irrelevant  went to go in george's room to find his door w...
21704    Positive         Yo this looks LIT! Team:GO/Overwatch combo
47008    Negative  Pay attention executive administrators. While ...
7969   Irrelevant  Guy looked at me and says my name was put on t...
454      Positive                                                one
...           ...                                                ...
7757     Positive                   i can play overwatch again (bad)
3887     Negative  The base weapons of black ops Cold War are so ...
22629     Neutral  Don'don t just jump me... @CSGO... is medal. t...
66836  Irrelevant  for FUCKS SAKE!!!!!!!! FIRST MONTH FOR ONE MON...
56434    Positive  New video later shoot premiere at 12 and its g...

[15000 rows x 2 columns]

In [13]:
# Remove null values
data.dropna(inplace=True)

In [14]:
data.isnull().sum()

Positive                                                 0
im getting on borderlands and i will murder you all ,    0
dtype: int64

In [15]:
# Remove duplicate values
data.drop_duplicates(inplace=True)

In [16]:
data.duplicated().sum()

np.int64(0)

In [17]:
# Change column names
data.rename(columns={'Positive': 'Sentiment', 'im getting on borderlands and i will murder you all ,': 'Tweets'}, inplace=True)

In [18]:
data.columns

Index(['Sentiment', 'Tweets'], dtype='str')

In [19]:
# Check final data shape
data.shape

(14445, 2)

In [20]:
# Remove Irrelevant sentiment from data
data = data[data['Sentiment'].isin(['Neutral', 'Positive', 'Negative'])]

In [21]:
data['Sentiment'].value_counts()

Sentiment
Negative    4342
Positive    4101
Neutral     3424
Name: count, dtype: int64

### Feature engineering & encoding

In [22]:
label = LabelEncoder()

In [23]:
# Apply label encoding to Sentiment column
data['Sentiment'] = label.fit_transform(data['Sentiment'])

In [24]:
data

       Sentiment                                             Tweets
21704          2         Yo this looks LIT! Team:GO/Overwatch combo
47008          0  Pay attention executive administrators. While ...
454            2                                                one
58076          0       @Rainbow6Game Server are Available in Xbox 🥺
40659          2  so Awesome siege attempt... strangest bleeding...
...          ...                                                ...
57537          2  This is not my nice way of saying what GN with...
7757           2                   i can play overwatch again (bad)
3887           0  The base weapons of black ops Cold War are so ...
22629          1  Don'don t just jump me... @CSGO... is medal. t...
56434          2  New video later shoot premiere at 12 and its g...

[11867 rows x 2 columns]

In [25]:
tokenizer = Tokenizer(oov_token='Noting')

In [26]:
# Apply tokenizer to Tweets column
tokenizer.fit_on_texts(data['Tweets'])

In [27]:
# Convert texts to sequences
sequences = tokenizer.texts_to_sequences(data['Tweets'])
sequences

[[590, 11, 199, 1676, 214, 95, 196, 2523],
 [308,
  2159,
  4021,
  4022,
  231,
  36,
  1001,
  29,
  791,
  898,
  1324,
  10,
  6516,
  7,
  6517,
  4,
  6518,
  145,
  15,
  247,
  193,
  436,
  9,
  1075,
  2,
  3481,
  7,
  2160,
  3095],
 [51],
 [153, 504, 29, 1002, 9, 99, 2321],
 [20,
  250,
  810,
  3096,
  4868,
  4023,
  33,
  2524,
  6519,
  152,
  115,
  13,
  149,
  10123,
  1677,
  243,
  101,
  2,
  2524,
  1516,
  244,
  28,
  250],
 [56, 54, 286, 466, 4, 2, 18],
 [90,
  10124,
  4024,
  919,
  831,
  118,
  14,
  2,
  190,
  2525,
  10125,
  6520,
  17,
  1771,
  190,
  467,
  90,
  969,
  232,
  4,
  4869,
  373,
  36,
  224,
  4,
  90,
  260,
  14,
  2525,
  2,
  6521],
 [10126, 15, 169, 29, 132, 721, 9, 2, 1882, 7, 6522],
 [113, 2, 87, 441, 111, 351, 368, 53, 83, 1163],
 [3, 58, 76, 196, 1256, 15, 650, 6, 50, 1164, 848, 10, 88, 254],
 [1003, 55, 3, 2790, 196],
 [100,
  467,
  28,
  722,
  47,
  2161,
  170,
  1116,
  2322,
  1517,
  32,
  2526,
  71,
  38,
  125,
  1203,
  600,
  66,
  66,
  2,
  2527,
  437,
  1454,
  2161,
  28,
  849,
  10127,
  107,
  319],
 [1678, 13, 3097, 7, 10128, 13, 1679, 6523, 6, 379, 369, 2, 263, 128],
 [46, 57, 850, 21, 9, 13, 851, 25, 11, 63, 66, 286, 660, 1676, 748, 66],
 [106,
  424,
  106,
  219,
  1772,
  116,
  448,
  105,
  26,
  3482,
  283,
  601,
  165,
  9,
  850,
  748,
  4870,
  283,
  31,
  10129,
  6524,
  10130,
  27,
  302,
  19,
  11,
  675,
  4871,
  99,
  10131,
  248,
  6525],
 [577, 68, 61, 183, 100, 41, 9],
 [643, 13, 10132, 171, 191, 7, 10133, 10134],
 [6526, 942, 12, 137, 706, 52, 79, 620, 3098, 4025, 6527, 1585, 40, 3099, 534],
 [48, 15, 492, 249, 33, 19, 6, 2526, 600, 3, 1773, 602, 15],
 [871,
  10135,
  45,
  45,
  5,
  1257,
  2528,
  2162,
  1117,
  10136,
  6528,
  17,
  141,
  1118,
  2791,
  10137,
  78,
  43,
  72,
  6529],
 [22, 749, 52, 591, 30, 103, 161, 10138, 2, 723, 1204, 40, 337],
 [3100, 4, 13, 644, 56, 284, 19, 11],
 [3,
  111,
  20,
  2792,
  37,
  162,
  11,
  343,
  193,
  346,
  53,
  116,
  277,
  136,
  173,
  20,
  4026],
 [125, 493, 348, 425, 5, 1680, 23, 1004, 9, 18, 5, 10, 100, 174],
 [792, 4027, 1005, 23, 10139, 2323, 6530, 1518, 126, 14, 79],
 [88, 449],
 [66, 505, 6531, 91, 252, 611, 5, 173, 683],
 [4872,
  2,
  50,
  212,
  10,
  51,
  7,
  119,
  175,
  2793,
  83,
  235,
  8,
  250,
  2008,
  220,
  21,
  2794,
  19,
  2,
  1325,
  7,
  311,
  2,
  332,
  8,
  289,
  4,
  138,
  2,
  219,
  100,
  29,
  170,
  62,
  5,
  62,
  159,
  128,
  185,
  5,
  4028,
  47,
  2,
  18],
 [2,
  10140,
  214,
  8,
  39,
  137,
  10141,
  30,
  1586,
  811,
  10142,
  230,
  123,
  10143,
  57,
  1119,
  15,
  535,
  37,
  3101,
  83,
  323,
  40,
  183,
  7,
  184,
  498,
  95,
  71,
  920,
  14,
  1586,
  1006,
  142,
  10,
  2,
  872,
  1883,
  17,
  10144],
 [2324,
  1326,
  2325,
  10145,
  2009,
  8,
  346,
  2,
  82,
  177,
  179,
  899,
  9,
  6,
  290,
  69,
  327,
  7,
  15,
  16,
  44,
  182,
  4029,
  661,
  333,
  18,
  19,
  182,
  2795,
  873,
  3102,
  220,
  147,
  16,
  11,
  10146,
  8,
  1034,
  40,
  3,
  49,
  6532,
  11,
  4,
  13,
  3483,
  274,
  7,
  88,
  3484,
  5,
  235,
  11,
  57,
  707,
  62,
  4873,
  2529,
  10147,
  5],
 [519,
  849,
  4030,
  10148,
  9,
  4874,
  10149,
  10150,
  970,
  6533,
  10151,
  1327,
  4875,
  91,
  46,
  10152,
  354,
  2,
  10153,
  7,
  2,
  467,
  10154,
  2326,
  3485,
  2796,
  6534,
  198,
  578,
  91,
  158,
  110,
  450,
  6,
  723,
  9,
  6535,
  6536,
  2530,
  1205,
  411,
  143],
 [26,
  64,
  7,
  127,
  29,
  23,
  3,
  97,
  4031,
  6537,
  5,
  261,
  2531,
  2163,
  37,
  2,
  116,
  30],
 [3,
  150,
  4,
  832,
  6,
  921,
  100,
  2532,
  6538,
  921,
  1774,
  4,
  6539,
  23,
  9,
  2,
  191,
  7,
  168,
  18,
  16,
  4876,
  750,
  8,
  6540,
  2533,
  1328],
 [650,
  7,
  2,
  269,
  180,
  10155,
  31,
  382,
  453,
  6541,
  49,
  562,
  9,
  1681,
  30,
  1775,
  7,
  62,
  130,
  922,
  4032,
  1258,
  468,
  3103,
  4,
  114,
  10156,
  17,
  2164,
  852,
  10157],
 [23,
  3,
  492,
  38,
  65,
  13,
  306,
  163,
  287,
  49,
  44,
  131,
  316,
  215,
  621,
  1682,
  369,
  121,
  6,
  163,
  5,
  27,
  38,
  1884,
  137,
  23,
  391,
  210,
  469,
  199,
  92],
 [536,
  197,
  2,
  176,
  96,
  84,
  144,
  31,
  1165,
  1455,
  494,
  6542,
  42,
  4,
  95,
  33,
  9,
  2797,
  34,
  35,
  17,
  10158],
 [140,
  150,
  4,
  349,
  159,
  212,
  651,
  302,
  10,
  900,
  177,
  550,
  676,
  442,
  355,
  1456,
  1259,
  10159],
 [470,
  1683,
  15,
  49,
  2165,
  169,
  10160,
  4033,
  22,
  88,
  10,
  6,
  10161,
  8,
  40,
  2010,
  40,
  12,
  8,
  874],
 [116,
  2534,
  1120,
  3,
  22,
  541,
  4,
  200,
  485,
  6,
  42,
  512,
  155,
  15,
  4,
  26,
  327,
  7,
  15,
  100,
  833,
  5,
  29,
  320,
  14,
  116,
  4877,
  5,
  2798,
  15,
  80,
  724,
  75,
  2535,
  12,
  6543,
  62,
  130,
  551,
  253,
  442,
  1457,
  39,
  76,
  12,
  26,
  529,
  24,
  75,
  309,
  1458,
  20,
  155,
  15],
 [853, 135, 426, 10162, 10163, 85, 6544, 854, 10164],
 [4878, 6, 198, 476, 19, 216, 248, 2, 17],
 [70, 32, 88, 135, 354, 6, 1166, 163, 287, 2166],
 [81,
  1121,
  2,
  99,
  180,
  171,
  4,
  21,
  13,
  175,
  3486,
  1587,
  398,
  6545,
  17,
  141,
  1260,
  1261,
  4879,
  4034],
 [2011, 4, 90, 5, 89, 2, 3104, 10165, 2167, 5, 125, 2, 82, 812, 152, 225],
 [438,
  2327,
  181,
  23,
  19,
  2,
  10166,
  1519,
  3,
  2327,
  1459,
  56,
  266,
  108,
  15,
  10167,
  4880,
  12,
  48,
  70,
  2168,
  56,
  10168,
  438,
  33],
 [923,
  10169,
  106,
  83,
  179,
  175,
  683,
  506,
  88,
  10170,
  2,
  6546,
  2169,
  10171,
  1885,
  1206,
  6547,
  96,
  84,
  144,
  1203,
  7,
  4881,
  2536,
  7,
  2,
  849,
  2328,
  10172,
  2537,
  4035,
  134,
  2799,
  23,
  10173,
  10174,
  10175,
  10176,
  10177,
  469],
 [6548,
  6549,
  22,
  89,
  2,
  901,
  725,
  834,
  26,
  5,
  167,
  10,
  193,
  250,
  10,
  2,
  2012,
  9,
  2,
  352,
  41,
  57,
  24,
  6,
  1207,
  74,
  141,
  5,
  2,
  250,
  4036,
  612],
 [19, 67, 6550, 47, 11],
 [9,
  6551,
  4882,
  875,
  7,
  288,
  2,
  6552,
  8,
  62,
  201,
  6,
  42,
  359,
  793,
  1460,
  2329,
  1007,
  9,
  1208,
  2330],
 [63],
 [140,
  9,
  13,
  297,
  24,
  3,
  541,
  4,
  275,
  6,
  332,
  3487,
  20,
  151,
  25,
  112,
  91,
  2,
  1886,
  241,
  8,
  140,
  9,
  708,
  114,
  876],
 [10178,
  2800,
  466,
  4,
  141,
  5,
  81,
  662,
  6,
  855,
  212,
  4,
  113,
  6,
  10179,
  10180,
  9,
  542,
  877,
  8,
  10181,
  40,
  6553,
  141,
  10182,
  53,
  1684,
  7,
  61,
  2170,
  12,
  8,
  14,
  794,
  6554,
  751,
  10183,
  10184,
  81,
  17,
  813,
  102,
  10185,
  157],
 [90,
  2801,
  4037,
  123,
  1775,
  1035,
  14,
  15,
  103,
  6555,
  5,
  31,
  77,
  320,
  37,
  103,
  5,
  15,
  29,
  123,
  107,
  902,
  167,
  10,
  304],
 [1685,
  2013,
  3488,
  4883,
  1887,
  451,
  121,
  10186,
  1776,
  6556,
  4884,
  479,
  1387,
  14,
  6557,
  530,
  10187],
 [13, 3489, 878, 10188, 57, 2538, 90],
 [11, 2, 176, 69, 298, 2539, 13, 69, 14, 317, 4038],
 [11, 28, 760, 338, 23, 150, 4, 1329, 13, 879],
 [48,
  6,
  178,
  18,
  943,
  6,
  178,
  18,
  1036,
  14,
  15,
  120,
  15,
  172,
  12,
  6,
  6558,
  3,
  213,
  4,
  172,
  4039,
  204,
  21,
  4885],
 [429, 429, 429, 429],
 [170, 52, 264, 417, 37, 507, 8, 2, 430, 232, 4, 38],
 [2802,
  10189,
  167,
  10,
  123,
  1167,
  4,
  486,
  924,
  202,
  2,
  178,
  4,
  101,
  48,
  15,
  356,
  6,
  360,
  79,
  709,
  303,
  663,
  1209,
  16,
  10,
  205,
  468,
  374,
  4,
  237,
  44,
  1262,
  95,
  726,
  39,
  10,
  6,
  237,
  240,
  106,
  10,
  1037,
  2803,
  880,
  2802,
  78,
  43,
  72,
  10190],
 [88,
  9,
  2,
  382,
  64,
  4886,
  7,
  191,
  7,
  168,
  8,
  20,
  2331,
  88,
  9,
  2,
  382,
  64,
  18,
  7,
  191,
  7,
  168,
  8,
  20,
  1330,
  88,
  9,
  2,
  382,
  64,
  4886,
  7,
  4040,
  7,
  168,
  8,
  20,
  2331,
  88,
  1888,
  2,
  382,
  64,
  4886,
  7,
  191,
  7,
  168,
  8,
  137,
  2331],
 [443, 881, 269, 248, 124, 412, 92, 1119, 3105, 2804, 1210, 4, 10191],
 [185, 460, 4, 21, 104, 121, 289, 61, 3, 58],
 [856,
  471,
  4,
  4041,
  5,
  1388,
  11,
  91,
  12,
  199,
  32,
  10192,
  8,
  87,
  226,
  1122,
  34,
  35,
  17,
  10193],
 [333, 124],
 [1076,
  7,
  6559,
  275,
  1777,
  1008,
  4,
  571,
  1389,
  354,
  45,
  45,
  6560,
  487,
  3490,
  7,
  448],
 [278,
  1390,
  3,
  58,
  36,
  83,
  1123,
  191,
  7,
  168,
  8,
  51,
  7,
  13,
  26,
  69,
  10194,
  83,
  3,
  22,
  58,
  12,
  182,
  374,
  3,
  243,
  357,
  1461,
  6,
  167,
  449],
 [579, 211, 12, 19, 2, 550, 408],
 [20, 622, 7, 13, 50, 6561, 6562, 4042],
 [2,
  176,
  814,
  7,
  380,
  168,
  28,
  6,
  1588,
  2540,
  10195,
  12,
  10196,
  78,
  72,
  10197],
 [944, 84, 21, 3106, 4, 23, 22, 971, 3, 89, 6, 79, 4043, 14],
 [8,
  835,
  258,
  312,
  186,
  945,
  129,
  613,
  835,
  267,
  4,
  138,
  795,
  7,
  2,
  128,
  6563,
  2014,
  5,
  260,
  170,
  2,
  443,
  426,
  761,
  14,
  258,
  223,
  277,
  34,
  1077,
  10198],
 [12, 8, 27, 2, 149, 69, 16, 2, 1009, 2541, 59, 1205, 323, 6, 1211],
 [4887, 155, 4044, 233, 3491, 14, 6564, 9, 2, 353, 288],
 [161,
  773,
  1778,
  29,
  468,
  82,
  4,
  96,
  562,
  3492,
  1038,
  403,
  9,
  30,
  603,
  85,
  6565],
 [262,
  56,
  238,
  270,
  628,
  3493,
  19,
  2,
  18,
  398,
  2805,
  4,
  24,
  6,
  2806,
  3494,
  318,
  3107,
  3495,
  4888,
  4889,
  4045,
  451,
  4890,
  383,
  2542,
  59,
  3108,
  326,
  31,
  3109,
  71,
  347,
  147,
  65,
  134,
  97,
  623,
  10199,
  115,
  2,
  258],
 [209,
  143,
  8,
  1779,
  9,
  1889,
  66,
  4,
  221,
  270,
  384,
  119,
  2171,
  9,
  11,
  92,
  812,
  74,
  6566,
  451,
  882],
 [836, 298, 4046, 2332],
 [41, 213, 6, 1212, 10, 404, 203, 444],
 [22,
  697,
  470,
  2807,
  186,
  2,
  1078,
  4,
  38,
  14,
  2,
  6567,
  76,
  10200,
  6,
  303,
  18,
  28,
  4,
  310,
  1462,
  6568,
  70,
  20,
  6569,
  4,
  101],
 [3,
  165,
  11,
  395,
  178,
  14,
  79,
  357,
  73,
  552,
  10,
  6,
  1391,
  4,
  237,
  508,
  534,
  79,
  9,
  18,
  480,
  10201],
 [129,
  98,
  9,
  11,
  227,
  212,
  438,
  1890,
  2,
  3496,
  752,
  186,
  46,
  601,
  75,
  16,
  232,
  11,
  333,
  134,
  445,
  2,
  18,
  55,
  15,
  49,
  22,
  384,
  14,
  6,
  6570,
  202,
  5,
  562,
  121,
  124,
  1520],
 [30,
  2,
  316,
  69,
  946,
  2,
  553,
  16,
  117,
  29,
  753,
  73,
  360,
  684,
  77,
  1263,
  1521,
  2,
  4891,
  752,
  175,
  7,
  131,
  63,
  27,
  24,
  645,
  4,
  592,
  837,
  5,
  63,
  27,
  24,
  645,
  4,
  592,
  425,
  231,
  175,
  7,
  131,
  63,
  27,
  24,
  645,
  4,
  592,
  425],
 [1392,
  117,
  8,
  52,
  3110,
  2796,
  2172,
  10,
  4047,
  4048,
  4892,
  6571,
  9,
  2,
  1780,
  2333,
  243,
  12,
  21,
  1124,
  16,
  10202,
  115,
  451,
  6572,
  97,
  972,
  2,
  383,
  7,
  2,
  2333,
  163,
  8,
  6573,
  71,
  125,
  186,
  4,
  2,
  1079,
  2326,
  1117,
  6574,
  159,
  1038,
  8,
  6575,
  664,
  135,
  6576,
  4049,
  4,
  361,
  219],
 [2],
 [56,
  9,
  6,
  513,
  878,
  7,
  710,
  203,
  39,
  25,
  3,
  24,
  4,
  200,
  12,
  28,
  1393,
  56,
  318,
  268,
  47,
  727,
  109,
  14,
  19,
  1125,
  203,
  39,
  3,
  328,
  51,
  128,
  477,
  21,
  6,
  387,
  7,
  12,
  26,
  61,
  6,
  6577,
  34,
  86,
  17,
  4893],
 [167, 262, 10, 1891, 23, 187, 6, 404, 18, 19, 53, 1331, 6578, 3111],
 [2, 87, 108, 761, 30, 2, 294, 7, 11, 8, 1891, 23],
 [1039,
  28,
  323,
  6,
  42,
  163,
  10,
  83,
  2543,
  196,
  217,
  85,
  6579,
  31,
  947,
  2173,
  64,
  2544,
  124,
  4050,
  31,
  318,
  773,
  392,
  198,
  6580,
  2174,
  6,
  1463,
  163],
 [148,
  514,
  148,
  393,
  22,
  1394,
  256,
  37,
  15,
  5,
  140,
  706,
  37,
  36,
  537,
  329,
  385,
  125,
  27,
  9,
  1168,
  63,
  3,
  38,
  4,
  1264,
  13,
  242,
  358,
  6581,
  11,
  8,
  815],
 [153,
  171,
  728,
  15,
  49,
  15,
  169,
  876,
  883,
  113,
  11,
  50,
  4894,
  18,
  394,
  2,
  4895,
  4896,
  1126,
  67,
  2545,
  2,
  762,
  18,
  838,
  74,
  16,
  26,
  3112,
  729,
  12,
  80,
  115,
  20,
  122,
  25,
  3,
  49,
  80,
  16,
  43,
  44,
  538],
 [730,
  26,
  1127,
  4,
  604,
  375,
  2,
  4051,
  86,
  629,
  5,
  108,
  4052,
  16,
  4897,
  33,
  145,
  373,
  77,
  451,
  10203,
  5,
  10204,
  126,
  614,
  11,
  8,
  133,
  774,
  1395,
  14,
  1686,
  102,
  834],
 [1589,
  452,
  48,
  15,
  29,
  27,
  554,
  4,
  731,
  3113,
  348,
  63,
  12,
  2015,
  903,
  36,
  4053,
  312,
  29,
  186,
  4054,
  677,
  25,
  15,
  38,
  224,
  37,
  3113,
  20,
  125,
  493],
 [472,
  413,
  10205,
  472,
  413,
  6582,
  61,
  2,
  2175,
  24,
  46,
  265,
  4,
  2,
  2334,
  6583,
  14,
  2,
  4898,
  10206,
  11,
  8,
  65,
  134,
  32,
  228,
  46,
  1590,
  19,
  311,
  16,
  1522,
  481,
  472,
  413,
  6582],
 [11,
  3497,
  8,
  142,
  3,
  58,
  1523,
  6584,
  630,
  19,
  2,
  1010,
  14,
  12,
  55,
  12,
  22,
  1121,
  4,
  200,
  16,
  13],
 [6585,
  22,
  450,
  116,
  64,
  37,
  13,
  3114,
  399,
  36,
  2335,
  652,
  652,
  49,
  80,
  14,
  43,
  754,
  139,
  4,
  181,
  310,
  2,
  499],
 [1524, 3, 49, 80, 43, 139, 10, 152, 13, 79, 2808],
 [79,
  177,
  22,
  1265,
  6,
  2160,
  605,
  23,
  216,
  6586,
  4055,
  17,
  141,
  1011,
  1261,
  2336],
 [61, 41, 58, 203, 39, 4056, 106, 1464, 283, 66, 95, 196],
 [159,
  69,
  400,
  44,
  10207,
  414,
  23,
  3,
  572,
  2,
  513,
  732,
  55,
  3,
  28,
  227,
  4,
  239,
  6587,
  2337,
  7,
  2,
  615,
  9,
  2,
  41,
  29,
  217,
  85,
  973,
  123,
  615,
  178,
  400,
  17,
  83,
  10208],
 [4899, 233, 42, 10, 2, 10209],
 [4, 6588, 3115, 9, 96, 84, 144, 31, 146, 118, 4057, 6589],
 [430, 2809, 10210, 4058, 175, 4900, 1266],
 [1267,
  408,
  82,
  305,
  1396,
  47,
  520,
  461,
  13,
  710,
  2338,
  15,
  112,
  82,
  1396,
  10,
  816,
  755,
  40,
  555,
  9,
  172,
  7,
  236,
  191,
  204,
  21,
  4901,
  4902],
 [85, 3, 58, 51, 198, 34, 35, 17, 6590],
 [61, 12, 200, 131, 453, 57, 2339, 19, 12, 195, 101, 12, 68, 170, 309, 66],
 [153,
  271,
  65,
  63,
  46,
  260,
  170,
  2,
  4059,
  665,
  624,
  32,
  6591,
  244,
  646,
  665,
  3,
  220,
  631,
  2176,
  4903,
  2176,
  578,
  775,
  32,
  252,
  403,
  37,
  51,
  2177,
  55,
  252,
  205,
  2,
  107,
  232,
  4,
  113,
  12,
  2178,
  8,
  4,
  359,
  1591,
  2,
  1592],
 [3,
  220,
  140,
  678,
  4904,
  4,
  774,
  2340,
  2179,
  1892,
  30,
  221,
  556,
  108,
  10,
  2016],
 [61, 6, 429, 128, 33, 3, 112, 139, 4, 725, 4060, 5, 44, 183, 7, 184],
 [370, 500],
 [923,
  6592,
  79,
  5,
  6593,
  66,
  430,
  6594,
  2795,
  10211,
  17,
  6595,
  3498,
  10212,
  6596,
  6597,
  66,
  10213,
  4061,
  10214,
  6598,
  6599,
  6600,
  1259],
 [6,
  10215,
  1268,
  6601,
  4,
  246,
  15,
  187,
  6,
  343,
  7,
  399,
  81,
  2546,
  539,
  10,
  267,
  4,
  6602,
  2,
  849,
  10216,
  9,
  36,
  723],
 [10217, 29, 2, 370, 241, 16, 49, 1525, 9, 6, 353, 288, 904, 6603, 5, 6604],
 [153, 182, 2180, 14, 170, 190, 2181, 521, 10218, 5, 67, 348, 24, 182],
 [3,
  110,
  6,
  285,
  62,
  69,
  4,
  44,
  2810,
  136,
  5,
  2,
  62,
  3,
  44,
  2,
  18,
  2,
  62,
  6605,
  3,
  111,
  16,
  11,
  18,
  8,
  2,
  227,
  234,
  241],
 [16, 2, 227, 1269, 57, 44, 87, 135],
 [217, 64, 1893, 5, 6, 217, 643, 4899, 21, 20, 284, 51, 128],
 [81, 10219, 419, 14, 756, 2547, 4, 2, 1462, 10220, 17, 81, 10221],
 [88,
  135,
  19,
  13,
  733,
  540,
  89,
  261,
  149,
  905,
  2182,
  354,
  23,
  5,
  67,
  299,
  201,
  356,
  80,
  43,
  857,
  60],
 [64, 94, 92, 18, 15, 89, 1593, 711, 113, 12, 34, 35, 17, 10222],
 [31,
  8,
  512,
  1894,
  40,
  3,
  208,
  58,
  2811,
  1895,
  137,
  188,
  3,
  601,
  165,
  105,
  7,
  131,
  121,
  16,
  685,
  51,
  199,
  974,
  748],
 [4062,
  1128,
  11,
  18,
  362,
  38,
  182,
  62,
  535,
  121,
  2,
  1465,
  53,
  1040,
  11,
  18,
  28,
  6,
  3499],
 [11,
  8,
  6,
  359,
  51,
  91,
  686,
  20,
  4063,
  3,
  57,
  357,
  4,
  6606,
  506,
  197,
  327,
  666,
  2341,
  6607,
  6608],
 [2, 82, 4905],
 [1041,
  173,
  266,
  21,
  20,
  6609,
  48,
  1397,
  74,
  852,
  6610,
  1213,
  14,
  2,
  1129,
  12,
  6611,
  430],
 [10223, 82, 580, 3116, 1781, 110, 2, 853, 679, 7, 70, 734, 735],
 [6612,
  876,
  1779,
  228,
  3,
  201,
  58,
  629,
  539,
  22,
  32,
  6613,
  5,
  6614,
  26,
  7,
  36,
  396,
  3,
  24,
  3,
  712,
  10224,
  5,
  3,
  58,
  12,
  32,
  3,
  58,
  228,
  3,
  6615,
  3,
  27,
  24,
  6,
  412,
  71,
  6,
  190,
  99,
  71,
  6,
  667,
  4064,
  3,
  107,
  3500,
  24,
  27,
  6,
  712,
  5,
  3,
  49,
  27,
  38,
  16,
  228,
  19,
  876,
  1779,
  12,
  3,
  3117,
  15,
  98,
  876],
 [1270, 223, 81, 975, 10225, 1782, 9, 366, 4906, 394, 2332, 17, 2017, 884],
 [364, 259, 58],
 [3, 111, 360, 111, 2342, 266, 776, 11, 166, 40, 431, 40, 12, 1169],
 [27, 107, 292, 86, 1594, 36, 839, 25, 70, 137, 92, 10, 2018],
 [6616,
  209,
  450,
  506,
  6,
  1012,
  7,
  116,
  64,
  18,
  454,
  2,
  250,
  4,
  1165,
  55,
  6617,
  4065,
  12,
  364,
  557,
  12],
 [1120,
  116,
  111,
  41,
  632,
  11,
  54,
  3118,
  98,
  10226,
  23,
  173,
  157,
  173,
  170,
  3119,
  231,
  2,
  383,
  1595,
  29,
  2812,
  46,
  1596,
  5,
  117,
  247,
  1332,
  26,
  630,
  65,
  8,
  11,
  6,
  241],
 [3501, 6618],
 [93, 593, 393, 135, 836, 298, 4907, 6619, 4066],
 [3, 57, 140, 678, 4904, 4, 774, 2340, 2179, 1892, 30, 108, 5, 215, 10, 2016],
 [88, 135, 8, 201, 2, 82, 130, 109, 4, 44, 10227, 9, 1597, 222],
 [2,
  1214,
  948,
  26,
  47,
  26,
  180,
  212,
  115,
  2813,
  212,
  39,
  2343,
  1264,
  1271,
  295,
  17,
  2164,
  177,
  99,
  141,
  78,
  43,
  72,
  6620],
 [687,
  6621,
  6622,
  10228,
  45,
  376,
  12,
  110,
  2178,
  1598,
  125,
  4067,
  355,
  713,
  6623,
  272,
  6624,
  78,
  43,
  72,
  6625],
 [11,
  177,
  47,
  2,
  114,
  4068,
  180,
  8,
  2,
  175,
  508,
  179,
  555,
  47,
  371,
  26,
  163,
  34,
  35,
  17,
  10229],
 [606,
  206,
  28,
  1170,
  757,
  10,
  494,
  4069,
  2,
  1042,
  600,
  5,
  2344,
  2,
  18,
  40,
  431,
  293,
  3,
  243,
  5,
  63,
  3,
  505,
  4908,
  1896,
  11,
  271,
  31],
 [2,
  633,
  387,
  8,
  16,
  117,
  29,
  239,
  62,
  10230,
  10231,
  130,
  3120,
  5,
  3120,
  244,
  6626,
  4,
  207,
  9,
  62,
  10232,
  6627,
  5,
  46,
  6628,
  102,
  26],
 [231,
  3,
  80,
  724,
  75,
  88,
  11,
  18,
  10,
  3502,
  2345,
  194,
  3,
  80,
  326,
  668,
  1599,
  7,
  12],
 [171, 81, 542, 976, 971, 3, 134, 24, 6, 321, 34, 35, 17, 10233],
 [6],
 [10234,
  8,
  13,
  3121,
  7,
  2019,
  6629,
  4909,
  2814,
  9,
  462,
  191,
  19,
  6,
  4070,
  10235,
  214,
  400,
  10236,
  129,
  613,
  835],
 [498, 1526, 2, 93, 60, 401, 41, 24, 6, 653, 4, 2346, 94, 34, 35, 17, 10237],
 [1327,
  124,
  572,
  20,
  15,
  24,
  137,
  240,
  645,
  4,
  796,
  7,
  92,
  81,
  531,
  15,
  49,
  310,
  19,
  55,
  36,
  885,
  37,
  103,
  127,
  2183,
  621,
  49,
  2548,
  26,
  15,
  62,
  9,
  289,
  22,
  16,
  257,
  171,
  272,
  3503],
 [4910,
  2815,
  15,
  346,
  348,
  425,
  25,
  49,
  15,
  63,
  98,
  98,
  181,
  858,
  33,
  119,
  398,
  219,
  5,
  152,
  977,
  414,
  153,
  3122,
  4,
  63,
  256,
  47,
  6630,
  91,
  95,
  623,
  43,
  23,
  46,
  29,
  289,
  364,
  304,
  98,
  181,
  102,
  46,
  634,
  80,
  1527,
  43,
  886,
  4,
  102,
  6,
  1466,
  32,
  23,
  244,
  8,
  594,
  439],
 [420,
  1215,
  495,
  205,
  421,
  65,
  11,
  900,
  2172,
  972,
  207,
  329,
  8,
  1130,
  27,
  6631],
 [12, 28, 3504, 100, 8, 2, 3505, 1272, 4071, 30, 16, 86],
 [2020, 854, 7, 43, 334],
 [48, 107, 2, 6632, 9, 2816, 218, 1216, 42],
 [501, 797, 79, 8, 109, 4, 93, 15, 19, 898],
 [81,
  925,
  39,
  3506,
  306,
  4072,
  121,
  2,
  1687,
  40,
  52,
  581,
  2,
  2817,
  1013,
  272,
  6633,
  78,
  72,
  6634],
 [3507,
  17,
  2021,
  1467,
  6635,
  4911,
  470,
  4073,
  4912,
  11,
  582,
  2549,
  926,
  2550,
  3,
  22,

In [28]:
# Apply padding to sequence of data for consistent input length
sequences = pad_sequences(sequences, padding='pre')

In [29]:
sequences

array([[    0,     0,     0, ...,    95,   196,  2523],
       [    0,     0,     0, ...,     7,  2160,  3095],
       [    0,     0,     0, ...,     0,     0,    51],
       ...,
       [    0,     0,     0, ...,    20,   222,  6161],
       [    0,     0,     0, ...,    43,    72, 17872],
       [    0,     0,     0, ...,   784,  1025,  6485]],
      shape=(11867, 99), dtype=int32)

### Train-Test Split

In [30]:
# Save tweets sequences into "X" and sentiment into "y"
X = sequences
y = data['Sentiment']

In [31]:
X

array([[    0,     0,     0, ...,    95,   196,  2523],
       [    0,     0,     0, ...,     7,  2160,  3095],
       [    0,     0,     0, ...,     0,     0,    51],
       ...,
       [    0,     0,     0, ...,    20,   222,  6161],
       [    0,     0,     0, ...,    43,    72, 17872],
       [    0,     0,     0, ...,   784,  1025,  6485]],
      shape=(11867, 99), dtype=int32)

In [32]:
y

21704    2
47008    0
454      2
58076    0
40659    2
        ..
57537    2
7757     2
3887     0
22629    1
56434    2
Name: Sentiment, Length: 11867, dtype: int64

In [33]:
# Split test-train data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [34]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((9493, 99), (2374, 99), (9493,), (2374,))

### Create a RNN model

In [ ]:
# vocab_size is the total number of unique words in the dataset + 1 (bcz index starts from 0)
vocab_size = len(tokenizer.word_index) + 1


model = Sequential([
    # Input(shape=(99,)),
    Embedding(input_dim=vocab_size, output_dim=128, input_length=99, mask_zero=True),
    SimpleRNN(32),
    Dense(3, activation='softmax') 
])

/home/linux/Desktop/projects/demos/vanilla-rnn/.venv/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(
E0000 00:00:1776428144.053387  195996 cuda_platform.cc:52] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)

In [36]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [37]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [43]:
model.fit(X_train, y_train, epochs=100, validation_data=(X_test, y_test),batch_size=64)

Epoch 1/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 10s 65ms/step - accuracy: 0.9890 - loss: 0.0285 - val_accuracy: 0.7047 - val_loss: 1.1491
Epoch 2/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 11s 67ms/step - accuracy: 0.9799 - loss: 0.0539 - val_accuracy: 0.7005 - val_loss: 1.1036
Epoch 3/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 15s 100ms/step - accuracy: 0.9878 - loss: 0.0332 - val_accuracy: 0.7237 - val_loss: 1.0893
Epoch 4/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 15s 102ms/step - accuracy: 0.9920 - loss: 0.0188 - val_accuracy: 0.7174 - val_loss: 1.1018
Epoch 5/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 20s 97ms/step - accuracy: 0.9921 - loss: 0.0165 - val_accuracy: 0.7161 - val_loss: 1.1244
Epoch 6/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 14s 93ms/step - accuracy: 0.9917 - loss: 0.0164 - val_accuracy: 0.7220 - val_loss: 1.1404
Epoch 7/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 14s 91ms/step - accuracy: 0.9919 - loss: 0.0157 - val_accuracy: 0.7178 - val_loss: 1.1753
Epoch 8/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 22s 100ms/step - accuracy: 0.9917 - loss: 0.0151 - val_accuracy: 0.7216 - val_loss: 1.1765
Epoch 9/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 19s 90ms/step - accuracy: 0.9918 - loss: 0.0149 - val_accuracy: 0.7258 - val_loss: 1.1932
Epoch 10/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 18s 75ms/step - accuracy: 0.9915 - loss: 0.0146 - val_accuracy: 0.7258 - val_loss: 1.2048
Epoch 11/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 24s 96ms/step - accuracy: 0.9925 - loss: 0.0147 - val_accuracy: 0.7270 - val_loss: 1.2234
Epoch 12/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 21s 98ms/step - accuracy: 0.9917 - loss: 0.0143 - val_accuracy: 0.7228 - val_loss: 1.2449
Epoch 13/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 13s 87ms/step - accuracy: 0.9917 - loss: 0.0145 - val_accuracy: 0.7174 - val_loss: 1.2604
Epoch 14/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 21s 88ms/step - accuracy: 0.9924 - loss: 0.0143 - val_accuracy: 0.7254 - val_loss: 1.2720
Epoch 15/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 14s 94ms/step - accuracy: 0.9918 - loss: 0.0141 - val_accuracy: 0.7220 - val_loss: 1.2856
Epoch 16/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 21s 94ms/step - accuracy: 0.9916 - loss: 0.0142 - val_accuracy: 0.7211 - val_loss: 1.3007
Epoch 17/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 22s 106ms/step - accuracy: 0.9925 - loss: 0.0140 - val_accuracy: 0.7241 - val_loss: 1.3096
Epoch 18/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 20s 103ms/step - accuracy: 0.9916 - loss: 0.0142 - val_accuracy: 0.7178 - val_loss: 1.3224
Epoch 19/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 14s 93ms/step - accuracy: 0.9915 - loss: 0.0143 - val_accuracy: 0.7216 - val_loss: 1.3269
Epoch 20/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 21s 95ms/step - accuracy: 0.9930 - loss: 0.0138 - val_accuracy: 0.7237 - val_loss: 1.3480
Epoch 21/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 20s 91ms/step - accuracy: 0.9926 - loss: 0.0138 - val_accuracy: 0.7233 - val_loss: 1.3467
Epoch 22/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 20s 90ms/step - accuracy: 0.9920 - loss: 0.0137 - val_accuracy: 0.7245 - val_loss: 1.3603
Epoch 23/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 18s 76ms/step - accuracy: 0.9926 - loss: 0.0135 - val_accuracy: 0.7127 - val_loss: 1.3946
Epoch 24/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 14s 95ms/step - accuracy: 0.9924 - loss: 0.0135 - val_accuracy: 0.7195 - val_loss: 1.3784
Epoch 25/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 13s 83ms/step - accuracy: 0.9924 - loss: 0.0135 - val_accuracy: 0.7199 - val_loss: 1.3872
Epoch 26/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 20s 81ms/step - accuracy: 0.9631 - loss: 0.0906 - val_accuracy: 0.7022 - val_loss: 1.2507
Epoch 27/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 16s 104ms/step - accuracy: 0.9726 - loss: 0.0745 - val_accuracy: 0.7220 - val_loss: 1.1513
Epoch 28/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 14s 62ms/step - accuracy: 0.9917 - loss: 0.0191 - val_accuracy: 0.7178 - val_loss: 1.1589
Epoch 29/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 9s 61ms/step - accuracy: 0.9925 - loss: 0.0145 - val_accuracy: 0.7220 - val_loss: 1.1709
Epoch 30/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 10s 59ms/step - accuracy: 0.9926 - loss: 0.0142 - val_accuracy: 0.7254 - val_loss: 1.1902
Epoch 31/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 10s 59ms/step - accuracy: 0.9927 - loss: 0.0137 - val_accuracy: 0.7245 - val_loss: 1.2075
Epoch 32/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 9s 58ms/step - accuracy: 0.9924 - loss: 0.0135 - val_accuracy: 0.7266 - val_loss: 1.2201
Epoch 33/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 9s 61ms/step - accuracy: 0.9926 - loss: 0.0135 - val_accuracy: 0.7262 - val_loss: 1.2369
Epoch 34/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 9s 59ms/step - accuracy: 0.9930 - loss: 0.0135 - val_accuracy: 0.7275 - val_loss: 1.2460
Epoch 35/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 11s 62ms/step - accuracy: 0.9928 - loss: 0.0134 - val_accuracy: 0.7279 - val_loss: 1.2585
Epoch 36/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 10s 64ms/step - accuracy: 0.9918 - loss: 0.0134 - val_accuracy: 0.7287 - val_loss: 1.2690
Epoch 37/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 11s 71ms/step - accuracy: 0.9927 - loss: 0.0132 - val_accuracy: 0.7279 - val_loss: 1.2841
Epoch 38/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 20s 70ms/step - accuracy: 0.9924 - loss: 0.0133 - val_accuracy: 0.7275 - val_loss: 1.2932
Epoch 39/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 20s 66ms/step - accuracy: 0.9928 - loss: 0.0131 - val_accuracy: 0.7270 - val_loss: 1.3071
Epoch 40/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 10s 65ms/step - accuracy: 0.9923 - loss: 0.0133 - val_accuracy: 0.7266 - val_loss: 1.3149
Epoch 41/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 10s 69ms/step - accuracy: 0.9924 - loss: 0.0132 - val_accuracy: 0.7262 - val_loss: 1.3225
Epoch 42/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 21s 71ms/step - accuracy: 0.9924 - loss: 0.0132 - val_accuracy: 0.7270 - val_loss: 1.3347
Epoch 43/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 12s 78ms/step - accuracy: 0.9924 - loss: 0.0131 - val_accuracy: 0.7245 - val_loss: 1.3445
Epoch 44/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 24s 104ms/step - accuracy: 0.9919 - loss: 0.0133 - val_accuracy: 0.7262 - val_loss: 1.3530
Epoch 45/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 15s 66ms/step - accuracy: 0.9926 - loss: 0.0132 - val_accuracy: 0.7233 - val_loss: 1.3597
Epoch 46/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 10s 65ms/step - accuracy: 0.9920 - loss: 0.0131 - val_accuracy: 0.7228 - val_loss: 1.3696
Epoch 47/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 10s 70ms/step - accuracy: 0.9924 - loss: 0.0131 - val_accuracy: 0.7245 - val_loss: 1.3801
Epoch 48/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 21s 71ms/step - accuracy: 0.9920 - loss: 0.0130 - val_accuracy: 0.7190 - val_loss: 1.3865
Epoch 49/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 22s 78ms/step - accuracy: 0.9923 - loss: 0.0131 - val_accuracy: 0.7169 - val_loss: 1.3941
Epoch 50/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 12s 83ms/step - accuracy: 0.9924 - loss: 0.0133 - val_accuracy: 0.7237 - val_loss: 1.4288
Epoch 51/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 19s 73ms/step - accuracy: 0.9923 - loss: 0.0135 - val_accuracy: 0.7178 - val_loss: 1.4472
Epoch 52/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 20s 73ms/step - accuracy: 0.9923 - loss: 0.0133 - val_accuracy: 0.7174 - val_loss: 1.4068
Epoch 53/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 15s 98ms/step - accuracy: 0.9927 - loss: 0.0130 - val_accuracy: 0.7195 - val_loss: 1.4206
Epoch 54/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 15s 60ms/step - accuracy: 0.9924 - loss: 0.0131 - val_accuracy: 0.7190 - val_loss: 1.4408
Epoch 55/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 9s 61ms/step - accuracy: 0.9925 - loss: 0.0128 - val_accuracy: 0.7161 - val_loss: 1.4291
Epoch 56/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 9s 60ms/step - accuracy: 0.9922 - loss: 0.0127 - val_accuracy: 0.7157 - val_loss: 1.4459
Epoch 57/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 10s 65ms/step - accuracy: 0.9927 - loss: 0.0127 - val_accuracy: 0.7190 - val_loss: 1.4507
Epoch 58/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 11s 74ms/step - accuracy: 0.9924 - loss: 0.0127 - val_accuracy: 0.7110 - val_loss: 1.4560
Epoch 59/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 18s 60ms/step - accuracy: 0.9920 - loss: 0.0126 - val_accuracy: 0.7161 - val_loss: 1.4744
Epoch 60/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 9s 61ms/step - accuracy: 0.9923 - loss: 0.0125 - val_accuracy: 0.7157 - val_loss: 1.4793
Epoch 61/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 10s 70ms/step - accuracy: 0.9923 - loss: 0.0126 - val_accuracy: 0.7174 - val_loss: 1.4987
Epoch 62/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 20s 69ms/step - accuracy: 0.9928 - loss: 0.0125 - val_accuracy: 0.7102 - val_loss: 1.4870
Epoch 63/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 21s 74ms/step - accuracy: 0.9924 - loss: 0.0125 - val_accuracy: 0.7157 - val_loss: 1.4974
Epoch 64/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 20s 71ms/step - accuracy: 0.9926 - loss: 0.0125 - val_accuracy: 0.7144 - val_loss: 1.5200
Epoch 65/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 11s 77ms/step - accuracy: 0.9929 - loss: 0.0123 - val_accuracy: 0.7131 - val_loss: 1.5126
Epoch 66/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 18s 59ms/step - accuracy: 0.9926 - loss: 0.0128 - val_accuracy: 0.7174 - val_loss: 1.4947
Epoch 67/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 11s 62ms/step - accuracy: 0.9925 - loss: 0.0123 - val_accuracy: 0.7148 - val_loss: 1.4912
Epoch 68/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 11s 71ms/step - accuracy: 0.9926 - loss: 0.0124 - val_accuracy: 0.7148 - val_loss: 1.5009
Epoch 69/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 21s 76ms/step - accuracy: 0.9928 - loss: 0.0123 - val_accuracy: 0.7140 - val_loss: 1.5046
Epoch 70/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 20s 71ms/step - accuracy: 0.9919 - loss: 0.0123 - val_accuracy: 0.7110 - val_loss: 1.5247
Epoch 71/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 20s 68ms/step - accuracy: 0.9926 - loss: 0.0123 - val_accuracy: 0.7140 - val_loss: 1.5539
Epoch 72/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 11s 71ms/step - accuracy: 0.9926 - loss: 0.0122 - val_accuracy: 0.7013 - val_loss: 1.5480
Epoch 73/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 13s 88ms/step - accuracy: 0.9833 - loss: 0.0416 - val_accuracy: 0.6811 - val_loss: 1.4305
Epoch 74/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 12s 84ms/step - accuracy: 0.9841 - loss: 0.0365 - val_accuracy: 0.7018 - val_loss: 1.3328
Epoch 75/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 11s 74ms/step - accuracy: 0.9918 - loss: 0.0168 - val_accuracy: 0.6921 - val_loss: 1.3522
Epoch 76/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 23s 87ms/step - accuracy: 0.9925 - loss: 0.0128 - val_accuracy: 0.6997 - val_loss: 1.3562
Epoch 77/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 18s 69ms/step - accuracy: 0.9928 - loss: 0.0122 - val_accuracy: 0.7009 - val_loss: 1.3663
Epoch 78/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 20s 69ms/step - accuracy: 0.9929 - loss: 0.0121 - val_accuracy: 0.7018 - val_loss: 1.3774
Epoch 79/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 10s 69ms/step - accuracy: 0.9928 - loss: 0.0121 - val_accuracy: 0.7047 - val_loss: 1.3853
Epoch 80/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 20s 65ms/step - accuracy: 0.9929 - loss: 0.0120 - val_accuracy: 0.7043 - val_loss: 1.3989
Epoch 81/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 10s 66ms/step - accuracy: 0.9929 - loss: 0.0121 - val_accuracy: 0.7064 - val_loss: 1.4033
Epoch 82/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 12s 82ms/step - accuracy: 0.9933 - loss: 0.0121 - val_accuracy: 0.7068 - val_loss: 1.4088
Epoch 83/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 23s 100ms/step - accuracy: 0.9924 - loss: 0.0121 - val_accuracy: 0.7072 - val_loss: 1.4208
Epoch 84/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 15s 99ms/step - accuracy: 0.9928 - loss: 0.0120 - val_accuracy: 0.7085 - val_loss: 1.4251
Epoch 85/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 15s 63ms/step - accuracy: 0.9932 - loss: 0.0120 - val_accuracy: 0.7085 - val_loss: 1.4330
Epoch 86/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 9s 63ms/step - accuracy: 0.9923 - loss: 0.0121 - val_accuracy: 0.7098 - val_loss: 1.4418
Epoch 87/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 10s 64ms/step - accuracy: 0.9923 - loss: 0.0121 - val_accuracy: 0.7081 - val_loss: 1.4475
Epoch 88/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 10s 66ms/step - accuracy: 0.9928 - loss: 0.0121 - val_accuracy: 0.7102 - val_loss: 1.4519
Epoch 89/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 11s 76ms/step - accuracy: 0.9932 - loss: 0.0120 - val_accuracy: 0.7064 - val_loss: 1.4612
Epoch 90/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 12s 81ms/step - accuracy: 0.9921 - loss: 0.0121 - val_accuracy: 0.7043 - val_loss: 1.4667
Epoch 91/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 25s 114ms/step - accuracy: 0.9930 - loss: 0.0120 - val_accuracy: 0.7094 - val_loss: 1.4700
Epoch 92/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 19s 103ms/step - accuracy: 0.9924 - loss: 0.0121 - val_accuracy: 0.7051 - val_loss: 1.4788
Epoch 93/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 12s 82ms/step - accuracy: 0.9924 - loss: 0.0122 - val_accuracy: 0.7072 - val_loss: 1.4834
Epoch 94/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 18s 66ms/step - accuracy: 0.9929 - loss: 0.0122 - val_accuracy: 0.7060 - val_loss: 1.4870
Epoch 95/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 10s 64ms/step - accuracy: 0.9924 - loss: 0.0121 - val_accuracy: 0.7060 - val_loss: 1.4982
Epoch 96/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 10s 66ms/step - accuracy: 0.9925 - loss: 0.0121 - val_accuracy: 0.7072 - val_loss: 1.5039
Epoch 97/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 10s 62ms/step - accuracy: 0.9932 - loss: 0.0120 - val_accuracy: 0.7056 - val_loss: 1.5138
Epoch 98/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 10s 59ms/step - accuracy: 0.9923 - loss: 0.0120 - val_accuracy: 0.7098 - val_loss: 1.5186
Epoch 99/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 9s 60ms/step - accuracy: 0.9928 - loss: 0.0121 - val_accuracy: 0.7085 - val_loss: 1.5287
Epoch 100/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 9s 61ms/step - accuracy: 0.9922 - loss: 0.0120 - val_accuracy: 0.7085 - val_loss: 1.5346

In [41]:
with open('tokenizer.pickle', 'wb') as file:
    pickle.dump(tokenizer, file)

In [44]:
model.save('sentiment_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.