### Basic RNN Deep Learning Model steps
1. Gather data
2. Preprocess & cleaning data
3. Feature engineering
4. Build a model
5. Save model into .h5 file
6. Load model from .h5 file

#### Import libraries

In [36]:
import pandas as pd
import tensorflow as tf

In [37]:
train_data = pd.read_csv('twitter_training.csv')

In [38]:
train_data.head()

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
0,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
1,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
2,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
3,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...
4,2401,Borderlands,Positive,im getting into borderlands and i can murder y...

In [39]:
train_data.shape

(74681, 4)

In [40]:
# We use only 15000 samples to train the model to save time.
data = train_data.sample(15000, random_state=42)

In [41]:
data.shape

(15000, 4)

In [42]:
data

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
34877,6792,Fortnite,Irrelevant,went to go in george's room to find his door w...
21704,4115,CS-GO,Positive,Yo this looks LIT! Team:GO/Overwatch combo
47008,5665,HomeDepot,Negative,Pay attention executive administrators. While ...
7969,9369,Overwatch,Irrelevant,Guy looked at me and says my name was put on t...
454,2476,Borderlands,Positive,one
...,...,...,...,...
7757,9333,Overwatch,Positive,i can play overwatch again (bad)
3887,1872,CallOfDutyBlackopsColdWar,Negative,The base weapons of black ops Cold War are so ...
22629,4275,CS-GO,Neutral,Don'don t just jump me... @CSGO... is medal. t...
66836,7044,johnson&johnson,Irrelevant,for FUCKS SAKE!!!!!!!! FIRST MONTH FOR ONE MON...
56434,11284,TomClancysRainbowSix,Positive,New video later shoot premiere at 12 and its g...

### Data exploration

In [43]:
# Check null values
data.isnull().sum()

2401                                                       0
Borderlands                                                0
Positive                                                   0
im getting on borderlands and i will murder you all ,    151
dtype: int64

In [48]:
# Check duplicate values
data.duplicated().sum()

np.int64(551)

In [ ]:
# Check positive column different values
data['Positive'].value_counts()

Positive
Negative      4488
Positive      4275
Neutral       3568
Irrelevant    2669
Name: count, dtype: int64

### Drop unwanted columns and cleaning data

In [44]:
data.drop(columns=['2401', 'Borderlands'], inplace=True)

In [45]:
data

         Positive im getting on borderlands and i will murder you all ,
34877  Irrelevant  went to go in george's room to find his door w...
21704    Positive         Yo this looks LIT! Team:GO/Overwatch combo
47008    Negative  Pay attention executive administrators. While ...
7969   Irrelevant  Guy looked at me and says my name was put on t...
454      Positive                                                one
...           ...                                                ...
7757     Positive                   i can play overwatch again (bad)
3887     Negative  The base weapons of black ops Cold War are so ...
22629     Neutral  Don'don t just jump me... @CSGO... is medal. t...
66836  Irrelevant  for FUCKS SAKE!!!!!!!! FIRST MONTH FOR ONE MON...
56434    Positive  New video later shoot premiere at 12 and its g...

[15000 rows x 2 columns]

In [ ]:
# Remove null values
data.dropna(inplace=True)

In [50]:
data.isnull().sum()

Positive                                                 0
im getting on borderlands and i will murder you all ,    0
dtype: int64

In [ ]:
# Remove duplicate values
data.drop_duplicates(inplace=True)

In [52]:
data.duplicated().sum()

np.int64(0)

In [54]:
# Change column names
data.rename(columns={'Positive': 'Sentiment', 'im getting on borderlands and i will murder you all ,': 'Tweets'}, inplace=True)

In [55]:
data.columns

Index(['Sentiment', 'Tweets'], dtype='str')

In [53]:
# Check final data shape
data.shape

(14445, 2)

In [57]:
# Remove Irrelevant sentiment from data
data = data[data['Sentiment'].isin(['Neutral', 'Positive', 'Negative'])]

In [60]:
data['Sentiment'].value_counts()

Sentiment
Negative    4342
Positive    4101
Neutral     3424
Name: count, dtype: int64

### Feature engineering